"""add document events

Revision ID: 5741b7502fb7
Revises: 018faf9f4d1b
Create Date: 2026-09-26 14:50:40.792168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5741b7502fb7'
down_revision: Union[str, Sequence[str], None] = '018faf9f4d1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.String(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('depth_m', sa.Float(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mitigation', sa.Text(), nullable=True),
    sa.Column('lesson', sa.Text(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_extraction_method', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['well_id'], ['wells_master.well_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_document_events_depth', 'document_events', ['depth_m'], unique=False)
    op.create_index('idx_document_events_document', 'document_events', ['document_id'], unique=False)
    op.create_index('idx_document_events_type', 'document_events', ['event_type'], unique=False)
    op.create_index('idx_document_events_well', 'document_events', ['well_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_document_events_well', table_name='document_events')
    op.drop_index('idx_document_events_type', table_name='document_events')
    op.drop_index('idx_document_events_document', table_name='document_events')
    op.drop_index('idx_document_events_depth', table_name='document_events')
    op.drop_table('document_events')
    # ### end Alembic commands ###
